services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - hackton-network
  
  
  hackton.web:
    image: hackton.web
    build:
      context: .
      dockerfile: Hackaton.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=postgres;Username=postgres;Password=test"
    depends_on:
      - postgres
    networks:
      - hackton-network
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = tech123
    networks:
      - hackton-network
    restart: always

networks:
  hackton-network:
    driver: bridge

